// ESLint 9 flat config.
//
// Two rule sets, and both matter for different reasons:
//
// - @n8n/eslint-plugin-community-nodes is what n8n's own scanner
//   (@n8n/scan-community-package) runs when a node is submitted for
//   verification. That scanner only accepts a *published* package name, so
//   without this config the only way to learn its verdict is to publish and
//   wait -- which is how five errors reached a submitted release.
//
// - eslint-plugin-n8n-nodes-base carries the older naming and structure rules
//   that the scanner does not cover.
//
// The official plugin pins eslint to exactly 9.29.0, which is why that version
// is pinned in devDependencies rather than ranged.
import { FlatCompat } from '@eslint/eslintrc';
import communityNodes from '@n8n/eslint-plugin-community-nodes';
import tsParser from '@typescript-eslint/parser';
import * as jsoncParser from 'jsonc-eslint-parser';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default [
	{
		ignores: [
			'dist/**',
			'node_modules/**',
			'**/*.js',
			'**/*.mjs',
			// Generated by scripts/build-properties.mjs. Linting it would report
			// on the shape of the API, not on anything written here.
			'nodes/WaAPI/properties.json',
			'nodes/WaAPI/openapi.json',
		],
	},

	// The rules n8n's submission scanner enforces.
	communityNodes.configs.recommended,

	// The older naming and structure rules, which are still eslintrc-style.
	...compat.extends('plugin:n8n-nodes-base/nodes').map((c) => ({
		...c,
		files: ['nodes/**/*.ts'],
	})),
	...compat.extends('plugin:n8n-nodes-base/credentials').map((c) => ({
		...c,
		files: ['credentials/**/*.ts'],
	})),

	{
		// package.json and the codex file are JSON. The official rule set reads
		// package.json, so they cannot simply be ignored -- they need a parser
		// that is not TypeScript's.
		files: ['**/*.json'],
		languageOptions: { parser: jsoncParser },
	},

	{
		files: ['**/*.ts'],
		languageOptions: {
			parser: tsParser,
			parserOptions: { project: ['./tsconfig.eslint.json'] },
		},
		rules: {
			// Expects a slug into n8n's own docs site, as the built-in
			// credentials use. A community node has no page there, so the field
			// holds a full URL -- and the rule's autofix rewrites
			// 'https://waapi.app/docs' to 'httpsWaapiAppDocs', which points
			// nowhere. Verified by running the fixer, not assumed.
			'n8n-nodes-base/cred-class-field-documentation-url-miscased': 'off',

			// The two rule sets contradict each other here: the official one
			// requires NodeConnectionTypes.Main and the older one requires the
			// string literal 'main'. n8n's submission scanner runs the official
			// one, so it decides; these two are the older plugin's outdated
			// view of the same question.
			'n8n-nodes-base/node-class-description-inputs-wrong-regular-node': 'off',
			'n8n-nodes-base/node-class-description-outputs-wrong': 'off',
		},
	},
];
