import {
	INodeProperties,
	INodeType,
	INodeTypeDescription,
	NodeConnectionTypes,
} from 'n8n-workflow';
// Generated by scripts/build-properties.mjs from nodes/WaAPI/openapi.json.
// Baked at build time rather than derived on load: verified community nodes are
// not allowed runtime dependencies. Run `npm run build` after touching the spec.
import generated from './properties.json';

const properties = generated as unknown as INodeProperties[];

// NodeConnectionTypes only exists from n8n-workflow 2.0.0. Reading .Main off it
// unconditionally throws on anything older -- the node then fails to load with
// "The specified package could not be loaded", which says nothing about the
// cause. The value is the string 'main' in both, so the fallback costs nothing
// and keeps the node loadable on older n8n installations.
const mainConnection = NodeConnectionTypes?.Main ?? ('main' as never);

export class WaAPI implements INodeType {
    description: INodeTypeDescription = {
        displayName: 'WaAPI',
        name: 'waapi',
        icon: { light: 'file:waapi.svg', dark: 'file:waapi.dark.svg' },
        group: ['transform'],
        version: 1,
        // An agent can legitimately drive this node: every operation is a
        // discrete messaging action with named parameters.
        usableAsTool: true,
        subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
        description: 'Interact with WaAPI API',
        defaults: {
            name: 'WaAPI',
        },
        inputs: [mainConnection],
        outputs: [mainConnection],
        credentials: [
            {
                name: 'waapiApi',
                required: true,
            },
        ],
        requestDefaults: {
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
            baseURL: 'https://waapi.app/api/v1',
        },
        properties: properties,
    };
}
