import { INodeProperties, INodeType, INodeTypeDescription } from 'n8n-workflow';
// Generated by scripts/build-properties.mjs from nodes/WaAPI/openapi.json.
// Baked at build time rather than derived on load: verified community nodes are
// not allowed runtime dependencies. Run `npm run build` after touching the spec.
import generated from './properties.json';

const properties = generated as unknown as INodeProperties[];

export class WaAPI implements INodeType {
    description: INodeTypeDescription = {
        displayName: 'WaAPI',
        name: 'waapi',
        icon: 'file:waapi.svg',
        group: ['transform'],
        version: 1,
        subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
        description: 'Interact with WaAPI API',
        defaults: {
            name: 'WaAPI',
        },
        inputs: ['main'],
        outputs: ['main'],
        credentials: [
            {
                name: 'waapiApi',
                required: true,
            },
        ],
        requestDefaults: {
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
            },
            baseURL: 'https://waapi.app/api/v1',
        },
        properties: properties,
    };
}
